# Shown as the "Sponsor" button on the repository page.
# The detail behind each option is in FUNDING.md; the commercial licence,
# sponsored sensor characterisation and consulting are arranged by email
# (s.rabykin@gmail.com) rather than through this file.
github: [lanserge]
