# Copyright 2026 Serge Rabyking
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
"""Export the revela ISP package for a picam2hdmi bridge.

Two packages share the bridge's module seam, split by what they are
allowed to touch. The SENSOR package is a driver: it writes its own
sensor's registers (integration, gains) and carries the sensor's
facts as data -- including the fitted ISP profile, as semantic
key/value pairs, never addresses. THIS package is the policy owner
and the only ISP-register writer: it owns the register map and the
cable's register channel, implements the bridge hooks, and calls
the sensor package through the driver ABI it publishes
(revela_sensor_api.h). Swap the sensor: one package changes. Swap
the ISP build: the other does.

The exporter bakes the register map into C at export time -- the
device parses nothing -- and the profile keys are revela's stable
block.param names, so a sensor package survives any register
relayout.

    python -m revela.host.bridge_module \\
        --regmap revela_isp.regmap.json --out revela-isp.tar.gz
"""
import argparse
import io
import json
import sys
import tarfile
import time
from pathlib import Path

SENSOR_API_H = '''\
/* The driver ABI between the revela ISP package (policy, the only
 * ISP-register writer) and a sensor package (a driver: writes its
 * OWN sensor's registers, carries its facts and its fitted ISP
 * profile as DATA). Published by the ISP package; a sensor package
 * ships an identical copy, and the manifests' provides/requires
 * pair is checked before anything compiles. */
#ifndef REVELA_SENSOR_API_H
#define REVELA_SENSOR_API_H
#include <stdint.h>

#define REVELA_SENSOR_API 1

/* fitted ISP parameters, by revela's stable block.param names --
 * semantic keys, never addresses; NULL key terminates */
struct revela_profile_entry {
    const char *key;
    int32_t value;
};

struct revela_sensor_driver {
    int api;                 /* REVELA_SENSOR_API */
    const char *name;
    const struct revela_profile_entry *profile;
    /* actuators for the exposure cascade; fd is the camera subdev.
     * A calibration-only package may leave any of these NULL. */
    int (*set_integration_lines)(int fd, uint32_t lines);
    int (*set_analog_gain)(int fd, uint32_t code);
    int (*set_digital_gain)(int fd, uint32_t code); /* NULL: no Gd */
};

/* implemented by the sensor package */
const struct revela_sensor_driver *revela_sensor(void);

#endif
'''


def generate_isp_c(regmap: dict) -> str:
    rows = []
    for b in regmap["blocks"]:
        for r in b["registers"]:
            rows.append((f"{b['path']}.{r['name']}", r["address"], r["bits"]))
    commit_addr = dict((k, a) for k, a, _ in rows)["pipe.commit"]

    L = []
    w = L.append
    w("/* generated by revela.host.bridge_module -- the ISP package:")
    w(" * the register map baked, the cable's register channel used,")
    w(" * the bridge hooks owned. The sensor package is a driver this")
    w(" * code calls; if none is installed, the hook says so and")
    w(" * touches nothing. */")
    w("#include <stdint.h>")
    w("#include <string.h>")
    w("#include <stdio.h>")
    w('#include "../../bridge.h"')
    w('#include "revela_sensor_api.h"')
    w("")
    w("/* the map: semantic key -> address and width. Its truth is the")
    w(" * receiver build's; the EDID gate below keeps a mismatched pair")
    w(" * from ever meeting. */")
    w("static const struct { const char *key; uint16_t reg; uint8_t bits; }")
    w("revela_map[] = {")
    for key, a, bits in sorted(rows, key=lambda x: x[1]):
        w(f'    {{ "{key}", 0x{a:04X}, {bits} }},')
    w("};")
    w(f"static const uint16_t revela_commit = 0x{commit_addr:04X};")
    w("")
    w("/* the sensor package is optional by construction: a weak")
    w(" * reference resolves to NULL when none is compiled in */")
    w("__attribute__((weak)) extern const struct revela_sensor_driver *")
    w("revela_sensor(void);")
    w("")
    w("void bridge_link_hook(const struct bridge_link *l) {")
    w("    if (!l->up || !l->edid) return;")
    w("    int ours = 0;")
    w("    for (int i = 0; i + 9 < 256; i++)")
    w('        if (!memcmp(l->edid + i, "BAYERLINK", 9)) { ours = 1; break; }')
    w("    if (!ours) {")
    w('        printf("revela: sink is not a bayerlink receiver; '
      'leaving it alone\\n");')
    w("        return;")
    w("    }")
    w("    if (!revela_sensor) {")
    w('        printf("revela: no sensor package installed -- the far '
      'end keeps its defaults\\n");')
    w("        return;")
    w("    }")
    w("    const struct revela_sensor_driver *drv = revela_sensor();")
    w("    if (!drv || drv->api != REVELA_SENSOR_API || !drv->profile) {")
    w('        printf("revela: sensor package present but unusable '
      '(api %d)\\n", drv ? drv->api : -1);')
    w("        return;")
    w("    }")
    w("    int wrote = 0, unknown = 0, failed = 0;")
    w("    for (const struct revela_profile_entry *e = drv->profile;")
    w("         e->key; e++) {")
    w("        int hit = 0;")
    w("        for (unsigned i = 0;")
    w("             i < sizeof revela_map / sizeof *revela_map; i++) {")
    w("            if (strcmp(revela_map[i].key, e->key)) continue;")
    w("            hit = 1;")
    w("            uint32_t mask =")
    w("                revela_map[i].bits >= 32")
    w("                    ? 0xFFFFFFFFu")
    w("                    : ((1u << revela_map[i].bits) - 1u);")
    w("            uint32_t v = ((uint32_t)e->value) & mask;")
    w("            if (bridge_ddc_write(revela_map[i].reg, v) == 0)")
    w("                wrote++;")
    w("            else failed++;")
    w("            break;")
    w("        }")
    w("        if (!hit) unknown++;")
    w("    }")
    w("    bridge_ddc_write(revela_commit, 1);")
    w("    uint32_t c = 1;")
    w("    for (int t = 0; t < 100 && c; t++)")
    w("        if (bridge_ddc_read(revela_commit, &c) < 0) break;")
    w('    printf("revela: %s: %d registers restored over the cable'
      '%s%s, commit %s\\n",')
    w("           drv->name, wrote,")
    w('           failed ? " (some FAILED)" : "",')
    w('           unknown ? " (some keys unknown to this build)" : "",')
    w('           c ? "PENDING" : "applied");')
    w("}")
    return "\n".join(L) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--regmap", required=True)
    parser.add_argument("--version", default="0.1")
    parser.add_argument("--out", default="revela-isp.tar.gz")
    args = parser.parse_args()

    regmap = json.loads(Path(args.regmap).read_text())
    files = {
        "manifest.json": json.dumps({
            "name": "revela-isp", "version": args.version,
            "kind": "picam2hdmi-module", "abi": 1,
            "slot": "isp",
            "provides": "revela-sensor-api:1",
            "sources": ["revela_isp.c"],
        }, indent=2) + "\n",
        "revela_sensor_api.h": SENSOR_API_H,
        "revela_isp.c": generate_isp_c(regmap),
    }
    with tarfile.open(args.out, "w:gz") as tar:
        for fname, data in files.items():
            b = data.encode()
            info = tarfile.TarInfo(fname)
            info.size = len(b)
            info.mtime = int(time.time())
            tar.addfile(info, io.BytesIO(b))
    print(f"{args.out}: revela-isp {args.version}, "
          f"map of {sum(len(b['registers']) for b in regmap['blocks'])} "
          f"registers baked, provides revela-sensor-api:1")
    return 0


if __name__ == "__main__":
    sys.exit(main())
