# Copyright 2026 Serge Rabyking
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
"""Export a sensor package for a picam2hdmi bridge.

The sensor package is a DRIVER: it writes its own sensor's
registers (integration time, gains -- through the camera subdev the
bridge already holds open) and carries the sensor's facts as data,
including the fitted ISP profile as semantic key/value pairs. It
never touches an ISP register and never sees a register map -- the
revela ISP package (the policy owner) calls it through
revela_sensor_api.h and does all far-end writing itself.

The generator mechanics live here in the open; the fitted profiles
and per-sensor descriptor data this consumes are the sensor
library's (revela-sensor-data).

    python -m revela.host.sensor_module \\
        --sensor ov5647 --profile profile.json --out sensor-ov5647.tar.gz
"""
import argparse
import io
import json
import sys
import tarfile
import time
from pathlib import Path

from .bridge_module import SENSOR_API_H


def generate_sensor_c(sensor: str, values: dict) -> str:
    L = []
    w = L.append
    w(f"/* generated by revela.host.sensor_module -- the {sensor}")
    w(" * package: a driver. Its own sensor's actuators through V4L2,")
    w(" * its fitted ISP profile as semantic keys -- data for the ISP")
    w(" * package to write; no register map, no far-end access. */")
    w("#include <stdint.h>")
    w("#include <stddef.h>")
    w("#include <sys/ioctl.h>")
    w("#include <linux/videodev2.h>")
    w('#include "revela_sensor_api.h"')
    w("")
    w("static const struct revela_profile_entry profile[] = {")
    for key, val in values.items():
        w(f'    {{ "{key}", {val} }},')
    w("    { 0, 0 },")
    w("};")
    w("")
    w("static int set_ctrl(int fd, uint32_t id, int32_t v) {")
    w("    struct v4l2_control c = { .id = id, .value = v };")
    w("    return ioctl(fd, VIDIOC_S_CTRL, &c) < 0 ? -1 : 0;")
    w("}")
    w("static int set_integration_lines(int fd, uint32_t lines) {")
    w("    return set_ctrl(fd, V4L2_CID_EXPOSURE, (int32_t)lines);")
    w("}")
    w("static int set_analog_gain(int fd, uint32_t code) {")
    w("    return set_ctrl(fd, V4L2_CID_ANALOGUE_GAIN, (int32_t)code);")
    w("}")
    w("")
    w("static const struct revela_sensor_driver drv = {")
    w("    .api = REVELA_SENSOR_API,")
    w(f'    .name = "{sensor}",')
    w("    .profile = profile,")
    w("    .set_integration_lines = set_integration_lines,")
    w("    .set_analog_gain = set_analog_gain,")
    w(f"    .set_digital_gain = 0,  /* {sensor}: gain finishes in the ISP */")
    w("};")
    w("")
    w("const struct revela_sensor_driver *revela_sensor(void) {")
    w("    return &drv;")
    w("}")
    return "\n".join(L) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sensor", required=True)
    parser.add_argument("--profile", default=None,
                        help="fitted values, semantic keys (block.param); "
                             "omit to use the built-in library "
                             "(revela/sensors/<sensor>/profile.json -- "
                             "ov5647 ships free as the reference; other "
                             "sensors' data lives in revela-sensor-data)")
    parser.add_argument("--version", default="0.1")
    parser.add_argument("--out", default=None)
    args = parser.parse_args()
    out = args.out or f"sensor-{args.sensor}.tar.gz"

    if args.profile:
        profile_path = Path(args.profile)
    else:
        profile_path = (Path(__file__).parent.parent / "sensors"
                        / args.sensor / "profile.json")
        if not profile_path.exists():
            print(f"no built-in profile for {args.sensor!r}: the free "
                  "library carries the reference sensor only; other "
                  "sensors' data comes from revela-sensor-data "
                  "(--profile PATH)", file=sys.stderr)
            return 2
    values = json.loads(profile_path.read_text())
    src = f"sensor_{args.sensor}.c"
    files = {
        "manifest.json": json.dumps({
            "name": f"sensor-{args.sensor}", "version": args.version,
            "kind": "picam2hdmi-module", "abi": 1,
            "slot": "sensor",
            "requires": "revela-sensor-api:1",
            "sources": [src],
        }, indent=2) + "\n",
        "revela_sensor_api.h": SENSOR_API_H,
        src: generate_sensor_c(args.sensor, values),
    }
    with tarfile.open(out, "w:gz") as tar:
        for fname, data in files.items():
            b = data.encode()
            info = tarfile.TarInfo(fname)
            info.size = len(b)
            info.mtime = int(time.time())
            tar.addfile(info, io.BytesIO(b))
    print(f"{out}: sensor-{args.sensor} {args.version}, "
          f"{len(values)} profile values, requires revela-sensor-api:1")
    return 0


if __name__ == "__main__":
    sys.exit(main())
